name: Build

on: push

jobs:
  test:
    strategy:
      matrix:
        php_version: [ '8.2', '8.3', '8.4' ]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print versions
        run: |
          php --version
          composer --version
          cat /etc/os-release

      - name: Composer install
        run: |
          composer install

      - name: PHP lint
        run: |
          shopt -s globstar
          php -l wp-content/plugins/mztx-wp-simple-et/*.php wp-content/plugins/mztx-wp-simple-et/**/*.php

      - name: Composer validate
        run: |
          composer validate

      - name: phpstan
        run: |
          php vendor/bin/phpstan analyse

  package:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write revision file
        run: |
          export VERSION="${GITHUB_REF#refs/*/v}"
          echo "$VERSION" > wp-content/plugins/mztx-wp-simple-et/REVISION
          sed -i "s/{{[[:space:]]*version[[:space:]]*}}/$VERSION/g" wp-content/plugins/mztx-wp-simple-et/mztx-wp-simple-et.php

      - name: Package release file
        run: |
          mkdir dist
          cd wp-content/plugins/mztx-wp-simple-et
          zip ../../../dist/mztx-wp-simple-et.zip *

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: dist/mztx-wp-simple-et.zip

      - name: Create pages dist
        run: mkdir ./dist_pages

      - name: Write update manifest
        run: |
          export VERSION="${GITHUB_REF#refs/*/v}"
          export DOWNLOAD_URL="${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }}"
          php build_plugin_update_manifest.php ./etc/update.tpl.json > ./dist_pages/update.json

      - name: Deploy update manifest to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist_pages
